// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJuVCS4fd8xEctqZpZv6ZKcAed4Xi9L7I',
    appId: '1:67171801998:web:fdf73cb8e7217e132ea2df',
    messagingSenderId: '67171801998',
    projectId: 'jobar-157a7',
    authDomain: 'jobar-157a7.firebaseapp.com',
    storageBucket: 'jobar-157a7.firebasestorage.app',
    measurementId: 'G-3C96L7X7VW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4bChO6UJwA7ZufAr861E_bAthoItrVyU',
    appId: '1:67171801998:android:e3bfd55d202300a72ea2df',
    messagingSenderId: '67171801998',
    projectId: 'jobar-157a7',
    storageBucket: 'jobar-157a7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD-tqlGgvb57Y6K_Tl2W7Xf92wIs9LzOyc',
    appId: '1:67171801998:ios:31682b9d83a93b6c2ea2df',
    messagingSenderId: '67171801998',
    projectId: 'jobar-157a7',
    storageBucket: 'jobar-157a7.firebasestorage.app',
    iosBundleId: 'com.example.jobarApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD-tqlGgvb57Y6K_Tl2W7Xf92wIs9LzOyc',
    appId: '1:67171801998:ios:31682b9d83a93b6c2ea2df',
    messagingSenderId: '67171801998',
    projectId: 'jobar-157a7',
    storageBucket: 'jobar-157a7.firebasestorage.app',
    iosBundleId: 'com.example.jobarApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJuVCS4fd8xEctqZpZv6ZKcAed4Xi9L7I',
    appId: '1:67171801998:web:9e3e4fb1623e5b8c2ea2df',
    messagingSenderId: '67171801998',
    projectId: 'jobar-157a7',
    authDomain: 'jobar-157a7.firebaseapp.com',
    storageBucket: 'jobar-157a7.firebasestorage.app',
    measurementId: 'G-XFYE12JL9Y',
  );
}
